### ISSUE TITLE
プレイ中BGM

### ISSUE THREAD

**Issue by ray45422** [ludumdare38-team-iruka/maingame#11]
プレイ中のBGMの制作

**Comment by tanitta** [comment]
コードへの組み込みお願いします．Game classのsetupでresources.loop("name.mp3")すると良いです．あとGame classのcheckFinishedの終了フラグが立つあたりでresources.close("name.mp3")してゲーム画面が終了する時に再生を止めてあげてください．

**Comment by OtObOx** [comment]
ファイル名はplay.mp3になります。
今日中には…

**Comment by OtObOx** [comment]
で、できた。あとは頼んだ…
