### ISSUE TITLE
カリスマ発揮中にオーラを表示する

### ISSUE THREAD

**Issue by OtObOx** [ludumdare38-team-iruka/maingame#120]
カリスマオーラがどこまで効果があるのかプレイヤーに伝わらないので、
カリスマ発揮中にオーラを表示する
カリスマオーラを発動していない場合は非表示に。
オーラは半透明で円？が表示されるといいかなーとか

**Comment by tanitta** [comment]
オーラの半径はminionのcalcVelocity()内の_r4の値です．maingameの方でグローバル変数として定義して，そちらの値を使うようにしてみてください．あと_r4の値も新しく定義したグローバル変数を代入していただけると助かります．

**Comment by tanitta** [comment]
やった
