### ISSUE TITLE
プレイ中のポーズ画面の実装

### ISSUE THREAD

**Issue by HoshiUmeko** [ludumdare38-team-iruka/maingame#125]
プレイ画面の時にポーズを実装する(一時停止）

必要
・文字のイラスト

**Comment by OtObOx** [comment]
文字のイラスト（たのみ済み！

**Comment by OtObOx** [comment]
スペースバーでポーズしてください！

**Comment by OtObOx** [comment]
ポーズ中の曲の扱い
案
１、曲を止める→再開時は続きから再生される（理想）
２、曲を止める→再開時は最初から再生される
３、曲の音量を下げる
４、何もしない。（流れたまま）→他の案が工数かかりそうならこれで

ポーズボタン押下時の効果音は明日朝に作ります。
ポーズ解除時も。

**Comment by ray45422** [comment]
https://github.com/ludumdare38-team-iruka/maingame/pull/158

**Comment by tanitta** [comment]
ポーズ機能は既に実装を終えたのであとはBGMの実装だけです．

**Comment by OtObOx** [comment]
ポーズ開始時の音がSE-8
ポーズ終了時の音がSE-9
desu!
