### ISSUE TITLE
たまごの実装

### ISSUE THREAD

**Issue by ray45422** [ludumdare38-team-iruka/maingame#18]
たまごのクラスを実装する

要議論:
たまごの孵る条件

**Comment by tanitta** [comment]
描画処理と卵が孵って魚になる処理は実装済み．

**Comment by tanitta** [comment]
あとは敵とのインタラクションを実装する必要がある

**Comment by tanitta** [comment]
インタラクションはうめさんが敵を実装した後に僕がやります

**Comment by tanitta** [comment]
音の追加は僕がやります

**Comment by tanitta** [comment]
卵と敵の接触時の処理実装しました．
次は卵が潰されたときの効果音の実装やります

**Comment by tanitta** [comment]
効果音実装しました
