### ISSUE TITLE
クレジット画面

### ISSUE THREAD

**Issue by ray45422** [ludumdare38-team-iruka/maingame#24]

**Comment by OtObOx** [comment]
仕様とか
ゲームクリア画面にてクリックすると「クレジット画面」が表示される
クレジット画面はデザイナーさんに一枚絵を書いてもらう→credit.png?
「クレジット画面」にて再度クリックするとタイトル画面へ遷移する。
タイトル画面へ遷移するとBGMをtitleへ切り替える
→クレジット画面中はクリア画面の曲になります。
クリックした際SE-4を再生する（1度だけ）
