### ISSUE TITLE
チュートリアル画面の実装

### ISSUE THREAD

**Issue by ray45422** [ludumdare38-team-iruka/maingame#3]
チュートリアルを表示する画面の実装

必要:
説明イラスト
(BGM)
PG実装

**Comment by tanitta** [comment]
ゲームの操作方法は24日の夜に決定するため，それまで確認用に使う差し替え可能な画像を追加しておいてください．

**Comment by OtObOx** [comment]
チュートリアル画面に表示するもの
・ゲームの目的
・操作方法

■ゲームの目的
仲間を集めて、卵を守る！

■操作方法
マウスに魚が付いてくる
王冠を取ればマウスクリックでみんなを呼び寄せられる

文字はなるべく書かない（英語解らない）ので、
これらをイラストで伝えることになります。

1,仲間が集まって敵から卵を守っている図
2,マウスカーソルに魚が付いてくる図
3,王冠を取ってクリックすればみんなを呼び寄せられる図

以上の3点が一枚の絵の中に入れば伝わるかと思います。
また表示上の問題で入りきらない場合は「2」をオミットしてください。
