### ISSUE TITLE
ゲームオーバー画面の実装

### ISSUE THREAD

**Issue by ray45422** [ludumdare38-team-iruka/maingame#4]
ゲームオーバーしたときの画面を実装

必要:
イラスト
BGM
PG実装

**Comment by OtObOx** [comment]
ゲームオーバーになる条件は以下の二つです。
・守っている卵がすべて食われたら終わり
・主となる魚が食べられると終わり

**Comment by tanitta** [comment]
ゲームオーバーのBGM，otoboさんお願いします．

**Comment by tanitta** [comment]
BGM上がり次第うめさん実装お願いします．

**Comment by tanitta** [comment]
ゲームオーバーの条件はGame本体側の処理なので，そっちのissue( #77 )で僕がやります．

**Comment by tanitta** [comment]
ゲーム条件の方終わりました．otoboさんBGMの作成引き続きお願いします．

**Comment by OtObOx** [comment]
ファイル名gameover.mp3になります。こちらの曲はループしません。
一度きりです。
うめさんお願いします。
