### ISSUE TITLE
各メニューのデザイン（これはデザイナーさんとプログラマーで決める）

### ISSUE THREAD

**Issue by OtObOx** [ludumdare38-team-iruka/maingame#43]
ゲーム内の配置デザイン
・タイトル→ゲームスタートの文字デザインとかも含め
・プレイ画面でのプレイヤーが取得できる情報表示のデザイン
・操作方法

**Comment by tanitta** [comment]
プレイ画面のUIの決定，otoboさんよろしくおねがいします:)

**Comment by OtObOx** [comment]
プレイ画面内に表示されるグラフィック
・スイミー
・取り巻き
・敵
・クラウン
以下は固定物
・カリスマゲージ
・背景
