### ISSUE TITLE
敵の行動パターン

### ISSUE THREAD

**Issue by OtObOx** [ludumdare38-team-iruka/maingame#48]
- [x] １．プレイヤーが守っているたまごを食べに行く。
- [ ] ２．プレイヤーの魚を食べに行く（とりまき→プレイヤーの順）
「１」を優先にする！
「２」の条件が作れるなら１と２は別の敵キャラクターにする（予定、工数次第）

**Comment by tanitta** [comment]
鼻先に卵が触れたら停止するようにしようとおもいます．

**Comment by tanitta** [comment]
2はやりません．
