### ISSUE TITLE
ゲームクリア画面の実装

### ISSUE THREAD

**Issue by ray45422** [ludumdare38-team-iruka/maingame#5]
ゲームクリア画面の実装

必要:
イラスト
BGM
PG実装

**Comment by tanitta** [comment]
slackのクリア画面をdataフォルダに追加してゲームオーバー画面のソースを参考に実装してください:)

**Comment by tanitta** [comment]
あとBGM上がり次第実装お願いします．

**Comment by OtObOx** [comment]
BGMあげました。clear.mp3になります。
クレジット画面からタイトル画面へ遷移時このBGMは止まる仕様です。
（クリア画面では止まらない）
