### ISSUE TITLE
カリスマ音の追加

### ISSUE THREAD

**Issue by tanitta** [ludumdare38-team-iruka/maingame#92]
マウスクリック時にカリスマを発揮しているときの音が欲しいです．otoboさんがSEを追加した後，うめさん実装お願いします．

**Comment by OtObOx** [comment]
SE-6になります

**Comment by OtObOx** [comment]
カリスマ音ですが発動中ずっとなっているとうるさく感じましたので、
発動時のみ再生されるようにお願いします。

**Comment by tanitta** [comment]
追加されたので実装おねがいします

**Comment by OtObOx** [comment]
ループにしたほうがとのことなのでEXSで考えます。

**Comment by OtObOx** [comment]
一応実装され、クリックする度に効果音が再生されるため閉じます。
ループはしません。
